version: 2.1

jobs:
  build:
    docker:
      - image: akhilrajmailbox/live-resume:1.0.1
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "01:95:a2:bd:af:19:58:a9:cc:47:e7:4c:be:59:a9:1d"
      - run:
          name: Install Packages
          command: |
            cp -r /opt/node_modules .
            npm run build-locale:liveResume --prod --aot
      - run:
          name: Update docs Folder
          command: mv docs/CNAME . && rm -rf docs && mkdir docs && cp -r dist/liveResume/en/* docs/ && mv CNAME docs/
      - run:
          name: Commit to GitHub
          command: bash circleci-script.sh

workflows:
  build_my_resume:
    jobs:
      - build